# Generated by Django 5.0.7 on 2024-08-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_ingresar',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
