# Generated by Django 5.0.7 on 2024-08-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='identificacion',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
