# Generated by Django 5.0.7 on 2024-08-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compras_usuario'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='producto',
        ),
        migrations.AddField(
            model_name='compras',
            name='productos',
            field=models.ManyToManyField(to='productos.producto'),
        ),
    ]
