# Generated by Django 5.0.7 on 2024-08-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_remove_compras_producto_compras_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='cantidad',
        ),
    ]
