# Generated by Django 5.0.7 on 2024-08-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_compras_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='productos',
            new_name='producto',
        ),
    ]
