# Generated by Django 5.0.7 on 2024-08-15 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_rename_productos_compras_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='producto',
            new_name='productos',
        ),
    ]
