# Generated by Django 5.0.7 on 2024-08-15 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_rename_producto_compras_productos'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='productos',
        ),
        migrations.AddField(
            model_name='compras',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compras',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
            preserve_default=False,
        ),
    ]
