# Generated by Django 5.0.7 on 2024-08-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_remove_compras_productos_compras_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='cantidad',
        ),
    ]
