# Generated by Django 5.0.7 on 2024-08-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_compraproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraproducto',
            name='compra',
        ),
    ]
