# Generated by Django 5.0.7 on 2024-08-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_remove_compraproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompraProducto',
        ),
    ]
