# Generated by Django 5.0.7 on 2024-08-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_delete_compraproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
